spring:
  config:
    import: "application-secret.yml"

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  application:
    name: service-discovery

  jackson:
    time-zone: Asia/Seoul

server:
  port: 8761
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-witjh-eureka-server: false # 유레카에 자신을 등록할지 여부
    fetch-registry: false # 유레카 서버에서 다른 서비스 정보를 가져올지 여부
    service-url:
        defaultZone: http://localhost:8761/eureka/ # 유레카 서버 주소

  server:
    wait-time-in-ms-when-sync-empty: 2000 # 유레카 서버가 비어있을 때 대기 시간

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
